;;; flashcard-bi.el

(defconst BI-DELIMITER " :<-> ")

(defconst BI-DUE-FORWARD-PROPERTY "BI_FORWARD_DUE")
(defconst BI-INTERVAL-FORWARD-PROPERTY "BI_INTERVAL_FORWARD")
(defconst BI-EASE-FACTOR-FORWARD-PROPERTY "BI_EASE_FACTOR_FORWARD")
(defconst BI-REPETITION-FORWARD-PROPERTY "BI_REPETITION_FORWARD")
(defconst BI-DUE-REVERSE-PROPERTY "BI_REVERSE_DUE")
(defconst BI-INTERVAL-REVERSE-PROPERTY "BI_INTERVAL_REVERSE")
(defconst BI-EASE-FACTOR-REVERSE-PROPERTY "BI_EASE_FACTOR_REVERSE")
(defconst BI-REPETITION-REVERSE-PROPERTY "BI_REPETITION_REVERSE")

(provide 'flashcard-bi)
